name: Tech Feed Bot

on:
  schedule:
    - cron: '0 * * * *'  # كل ساعة
  push:
    branches: [ main ]

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run bot
        run: python main.py
        env:
          RUN_MAIN: "true"
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
